## Electrical energy prediction using ANN

# Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

# Importing Dataset

In [ ]:
dataset=pd.read_excel('Folds5x2_pp.xlsx')
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


# Splitting dataset into training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


# Building ANN 

# Initializing ANN

In [ ]:
ann=tf.keras.Sequential()

# Creating input layer and First hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

# Creating Second hidden Layer



In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

# Creating Output Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

# Compiling ANN

In [ ]:
ann.compile(optimizer='adam',loss='mean_squared_error')

# Training ANN on training set

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 29914.0840
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 460.9749
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 439.2711
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 412.6861
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 382.5992
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 351.2068
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 317.3444
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 284.7652
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 251.5412
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 220.8513
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 191.7756
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - lo

# Predicting the results of test set

In [ ]:
y_pred=ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[433.91 431.23]
 [464.92 460.01]
 [468.39 461.14]
 ...
 [475.67 473.26]
 [442.35 438.  ]
 [461.59 463.28]]
